images:
  server_image:
    repository: riceheadv8/hyos
    tag: "1.0.0"
  manager_image:
    repository: riceheadv8/hyos-manager
    tag: "1.0.0"

consts:
  server_container_name: hytale-server
  manager_container_name: hytale-manager
  perms_container_name: hytale-perms
  data_path: /data
