images:
  image:
    repository: ghcr.io/editmysave/hyos/server
    tag: 0.0.2
  manager_image:
    repository: ghcr.io/editmysave/hyos/manager
    tag: 0.0.2
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  server_container_name: hytale-server
  manager_container_name: hytale-manager
  perms_container_name: hytale-perms
  data_path: /data
  internal_game_port: 5520
  internal_api_port: 8080
  internal_manager_port: 3000
